from typing import ClassVar

import numpy
from numpy.typing import NDArray

class SokobanGameState:
    name: ClassVar[str] = ...  # read-only
    num_actions: ClassVar[int] = ...  # read-only
    def __init__(self, board_str: str) -> None: ...
    def __copy__(self) -> SokobanGameState: ...
    def __deepcopy__(self, arg0: dict) -> SokobanGameState: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    def apply_action(self, int: int) -> None: ...
    def is_solution(self) -> bool: ...
    def is_terminal(self) -> bool: ...
    def observation_shape(self) -> tuple[int, int, int]: ...
    def get_observation(self) -> NDArray[numpy.float32]: ...
    def image_shape(self) -> tuple[int, int, int]: ...
    def to_image(self) -> NDArray[numpy.uint8]: ...
    def get_reward_signal(self) -> int: ...
    def get_agent_index(self) -> int: ...
    def get_box_indices(self) -> list[int]: ...
    def get_empty_goal_indices(self) -> list[int]: ...
    def get_solved_goal_indices(self) -> list[int]: ...
    def get_all_goal_indices(self) -> list[int]: ...
